#!/bin/bash -xe
sudo -u ubuntu -i <<'EOF'
REPO_OWNER=azureaws
REPO_NAME=jenkins-ansible-windows
RUNNER_LABELS="self-hosted,linux,X64" 
sudo apt update -y
sudo apt install docker -y
sudo apt install git -y
sudo apt install jq -y 
mkdir actions-runner
cd actions-runner
curl -o actions-runner-linux-x64-2.307.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.307.1/actions-runner-linux-x64-2.307.1.tar.gz
echo "038c9e98b3912c5fd6d0b277f2e4266b2a10accc1ff8ff981b9971a8e76b5441  actions-runner-linux-x64-2.307.1.tar.gz" | shasum -a 256 -c
tar xzf ./actions-runner-linux-x64-2.307.1.tar.gz
PAT=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
RUNNER_TOKEN=$(curl -s -XPOST \
    -H "authorization: token $PAT" \
    https://api.github.com/repos/REPO_OWNER/REPO_NAME/actions/runners/registration-token |\
    jq -r .token)
# Configure the runner
./config.sh --url https://github.com/$REPO_OWNER/$REPO_NAME --token $RUNNER_TOKEN --work "_work" --labels RUNNER_LABELS --unattended
sudo ./svc.sh install
sudo ./svc.sh start
git clone https://github.com/$REPO_OWNER/$REPO_NAME
cd $REPO_NAME
cp host.sh /home/ubuntu
EOF
