#!/bin/bash
sudo -u ubuntu -i <<'EOF'
REPO_OWNER=azureaws
REPO_NAME=jenkins-ansible-windows
ACCESS_TOKEN=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

# Install dependencies
sudo apt update -y
sudo apt install -y git

# Get a new GitHub token with 'repo' scope 
# GitHub API endpoint to create a repository token
API_URL="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runners/registration-token"

# Request the token from the GitHub API
RESPONSE=$(curl -X POST -H "Authorization: token $ACCESS_TOKEN" $API_URL)

# Extract the token from the JSON response
TOKEN=$(echo "$RESPONSE" | grep -oP '(?<="token": ")[^"]*')

# Print the token
GITHUB_TOKEN=$TOKEN
echo "Repository-specific runner token: $TOKEN"

# Download and configure the GitHub Actions runner
mkdir actions-runner && cd actions-runner# Download the latest runner package
curl -o actions-runner-linux-x64-2.307.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.307.1/actions-runner-linux-x64-2.307.1.tar.gz
# Optional: Validate the hash
echo "038c9e98b3912c5fd6d0b277f2e4266b2a10accc1ff8ff981b9971a8e76b5441  actions-runner-linux-x64-2.307.1.tar.gz" | shasum -a 256 -c# Extract the installer
tar xzf ./actions-runner-linux-x64-2.307.1.tar.gz

# Configure the runner
./config.sh --url https://github.com/$REPO_OWNER/$REPO_NAME --token $GITHUB_TOKEN --work "_work" --unattended


# Install dependencies
./bin/installdependencies.sh

# Start the runner as a service
sudo ./svc.sh install
sudo ./svc.sh start
git clone https://github.com/$REPO_OWNER/$REPO_NAME
cd $REPO_NAME
cp host.sh /home/ubuntu
EOF
