#!/bin/bash
sudo -u ubuntu -i <<'EOF'
REPO_OWNER=azureaws
REPO_NAME=jenkins-ansible-windows
RUNNER_TOKEN=A7J2MFW546VKI3U3MROZHP3ES6GYK
LABELS=selfhosted,Linux,X64

# Install dependencies
sudo yum update -y
sudo yum install -y git

# Download and configure the GitHub Actions runner
mkdir actions-runner && cd actions-runner# Download the latest runner package
curl -o actions-runner-linux-x64-2.305.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.305.0/actions-runner-linux-x64-2.305.0.tar.gz# Optional: Validate the hash
echo "737bdcef6287a11672d6a5a752d70a7c96b4934de512b7eb283be6f51a563f2f  actions-runner-linux-x64-2.305.0.tar.gz" | shasum -a 256 -c# Extract the installer
tar xzf ./actions-runner-linux-x64-2.305.0.tar.gz

# Configure the runner
./config.sh --url https://github.com/$REPO_OWNER/$REPO_NAME --token $RUNNER_TOKEN --labels $LABELS --unattended

# Start the runner as a service
sudo ./svc.sh install
sudo ./svc.sh start
EOF
