#!/bin/bash
sudo -u ubuntu -i <<'EOF'
REPO_OWNER=azureaws
REPO_NAME=jenkins-ansible-windows
RUNNER_TOKEN=A7J2MFXQR7OGSXCUQWFAZBDESZO62
LABELS=selfhosted,Linux,X64

# Install dependencies
sudo yum update -y
sudo yum install -y git

# Download and configure the GitHub Actions runner
# Create a folder
mkdir actions-runner && cd actions-runner# Download the latest runner package
curl -o actions-runner-osx-x64-2.305.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.305.0/actions-runner-osx-x64-2.305.0.tar.gz# Optional: Validate the hash
echo "a7c623e013f97db6c73c27288047c1d02ab6964519020ad0e87e69c328e96534  actions-runner-osx-x64-2.305.0.tar.gz" | shasum -a 256 -c# Extract the installer
tar xzf ./actions-runner-osx-x64-2.305.0.tar.gz

# Configure the runner
./config.sh --url https://github.com/$REPO_OWNER/$REPO_NAME --token $RUNNER_TOKEN --labels $LABELS --unattended

# Start the runner as a service
sudo ./svc.sh install
sudo ./svc.sh start
EOF
