#!/bin/bash -xe
apt update -y
apt install docker -y
apt install git -y
apt install jq -y 
sudo usermod -a -G docker ubuntu
sudo systemctl start docker
sudo systemctl enable docker
export RUNNER_ALLOW_RUNASROOT=true
mkdir actions-runner
cd actions-runner
curl -O -L https://github.com/actions/runner/releases/download/v2.262.1/actions-runner-linux-x64-2.262.1.tar.gz
tar xzf ./actions-runner-linux-x64-2.262.1.tar.gz
PAT=<Super Secret PAT>
token=$(curl -s -XPOST \
          -H "authorization: token $PAT" \
          https://api.github.com/repos/<GitHub_User>/<GitHub_Repo>/actions/runners/registration-token |\
          jq -r .token)
sudo chown ubuntu -R /actions-runner
./config.sh --url https://github.com/<GitHub_User>/<GitHub_Repo> --token $token --name "my-runner-$(hostname)" --work _work
sudo ./svc.sh install
sudo ./svc.sh start
sudo chown ubuntu -R /actions-runner
