name: Install Ansible

on:
  push:
    branches:
      - main

jobs:
  install-ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'

      - name: Install Ansible
        run: |
          pip install ansible
          ansible --version
          touch /etc/ansible/ansible.cfg
