on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted      
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python and python pip
        run: sudo apt-get install python3 -y && sudo apt-get install python3-pip -y
      
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install software-properties-common && sudo apt-add-repository --yes --update ppa:ansible/ansible&&sudo apt-get install -y ansible

   
      - name: Install boto3 library
        run: sudo apt-get install python-boto3

      - name: Configure SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure the inventory
        run: |
                sudo mkdir -p /opt/ansible/inventory
                cd /opt/ansible/inventory
                echo "plugin: aws_ec2
                      regions:
                        - "us-east-1"keyed_groups:
                        - key: tags.Name
                        - key: tags.task
                      filters:
                        instance-state-name : running
                      compose:
                        ansible_host: 44.201.169.219" >inventory_aws_ec2.yaml
      - name: Setup ansible configuration file with the required inventory
        run: |
          sed -i '/defaults/a enable_plugins = aws_ec2' /etc/ansible/ansible.cfg
          
      - name: Test the dynamic inventory configuration
        run: |
          ansible-inventory --graph -i inventory_aws_ec2.yml
          ansible all -m ping
          
          
        
