name: Ansible Windows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      - name: Install sshpass
        run: sudo apt install sshpass

      - name: Configure SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}


     
      - name: Run Ansible playbook
        run: |
           ansible -i inventory -m win_ping win
