name: Install Ansible

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Repo Ansible
        run: |
          sudo apt-get update && sudo apt install software-properties-common && sudo apt-add-repository --yes --update ppa:ansible/ansible
     
      - name: Install  Ansible and Check version
        run: |
          sudo apt install ansible -y && ansible --version
          
      - name: Install Python
        run: |
          if ! command -v python3 &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y python3
          fi
          python3 --version
          
      - name: Install Python Pip,Boto3 and other dependencies
        run: |
           sudo apt-get update && sudo apt-get install python3-pip -y
           sudo apt-get install python3-winrm -y && sudo sudo pip3 install boto3
      - name: Setup dynamic inventory
        run: |
           sudo mkdir -p /opt/ansible/inventory
           cd /opt/ansible/inventory
           echo "---
           plugin: aws_ec2
            regions:
            - "us-east-1"
            keyed_groups:
               - key: tags.Name
            filters:
             instance-state-name : running
             tag:type: mywinnode
             compose:
                ansible_host: public_ip_address" | sudo tee -a aws_ec2.yaml
              cat aws_ec2.yaml
      - name: Setup Ansible configuration
        run: |
           echo "[defaults]
           enable_plugins = aws_ec2
           inventory = /opt/ansible/inventory/aws_ec2.yaml" | sudo tee -a /etc/ansible/ansible.cfg
           cat /etc/ansible/ansible.cfg
           
      - name: Check the dynamic inventory 
        run: |
           ansible all --list-hosts
           
      - name: Generate host file for dynamic inventory
        run: |
          cd /etc/ansible
          sudo chmod +x inventory.sh
          sudo sh inventory.sh
          #Print inventory
          cat inventory.ini
 

      - name: Run Ansible playbook
        run: |
           ansible -i /etc/ansible/inventory.ini -m win_ping win
           ansible-playbook -i /etc/ansible/inventory.ini windowsplaybook.yaml
