name: Test Ansible Play

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Repo Ansible
        run: |
          sudo apt-get update && sudo apt-get install software-properties-common -y && sudo apt-add-repository --yes --update ppa:ansible/ansible
     
      - name: Check Ansible Installation
        id: check_ansible
        run: |
          ansible --version >/dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "Ansible is installed"
            echo "::set-output name=ansible_installed::true"
          else
            echo "Ansible is not installed"
            echo "::set-output name=ansible_installed::false"
          fi
      - name: Install Ansible
        if: steps.check_ansible.outputs.ansible_installed == 'false'
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          
      - name: Install Python
        run: |
          if ! command -v python3 &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y python3
          fi
          python3 --version
          
      - name: Install Python Pip,Boto3 and other dependencies
        run: |
           sudo apt-get update && sudo apt-get install python3-pip -y
           sudo apt-get install python3-winrm -y && sudo sudo pip3 install boto3
     
      - name: Set the dynamic inventory directory and check inventory file if it exists
        run: |
           sudo mkdir -p /opt/ansible/inventory
           cd /opt/ansible/inventory
           if [ -f aws_ec2.yaml]; then
                echo "Dynamic inventory setup"
                echo "::set-output name=file_exists::true"
             else
                echo "Dynamic inventory needs to be setup"
                echo "::set-output name=file_exists::false"
             fi
      - name: Setup dynamic inventory
        if: steps.check_file.outputs.file_exists == 'false'
        run: |
           echo "plugin: aws_ec2
                 regions:
                   - "us-east-1"
                 keyed_groups:
                   - key: tags.Name
                 filters:
                   instance-state-name : running
                   tag:type: mywinnode
                 compose:
                   ansible_host: public_ip_address"| sudo tee -a aws_ec2.yaml
                cat aws_ec2.yaml
                
      - name: Check Ansible Configuration
        id: check_string
        run: |
          if grep -q "inventory" /etc/ansible/ansible.cfg; then
            echo "Dynamic inventory defined"
            echo "::set-output name=string_found::true"
          else
            echo "Dynamic inventory not defined in ansible configuration"
            echo "::set-output name=string_found::false"
          fi
                
                
      - name: Define Dynamic inventory configuration
        if: steps.check_file.outputs.file_exists == 'false'
        run: |
           echo "[defaults]
           enable_plugins = aws_ec2
           inventory = /opt/ansible/inventory/aws_ec2.yaml" | sudo tee -a /etc/ansible/ansible.cfg
           fi
           cat /etc/ansible/ansible.cfg
           
      - name: Check the dynamic inventory 
        run: |
           ansible all --list-hosts
