name: Ansible Windows Playbook Updated

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Configure SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Create host file for generated dynamic inventory
        id: create_host
        run: |
          cd /etc/ansible
          ansible-inventory --list|grep -o '"public_ip_address": "[^"]*'|awk -F': "' '{print $2}' > hosts.txt
          hosts_file="hosts.txt"
          inventory_file="inventory.ini"
          # Check if the hosts file exists
          if [ -f "$hosts_file" ]; then
          # Create an inventory file
            echo "[win]" > "$inventory_file"
            # Read the hosts from the file and append them to the inventory file
          while IFS= read -r host
          do
          echo "$host" >> "$inventory_file"
          done < "$hosts_file"
          echo "Inventory file generated: $inventory_file"
          else
          echo "Hosts file not found: $hosts_file"
          fi
      
      #Otherway
      #- name: Generate host file for dynamic inventory
       # run: |
       #  cd /etc/ansible
        #  sudo chmod +x inventory.sh
         # sudo sh inventory.sh
          #Print inventory
          #cat inventory.ini
 

      - name: Run Ansible playbook
        run: |
           ansible -i /etc/ansible/inventory.ini -m win_ping win
           ansible-playbook -i /etc/ansible/inventory.ini windowsplaybook.yaml
