name: Ansible Windows Updated

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Configure SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Generate host file for dynamic inventory
        run: |
          cd /etc/ansible
          sudo sh inventory-ge.sh
          #Check if inventory is generated 
           if [ -f inventory.ini]; then
            echo "Inventory generated"
            cat inventory.ini
          else
            echo "Inventory File not found!"
          fi

      - name: Run Ansible playbook
        run: |
           ansible -i inventory.ini -m win_ping win
           ansible-playbook -i inventory.ini windowsplaybook.yaml
