name: Execute Ansible Playbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Execute Ansible playbook
        run: |
          ansible-playbook playbook.yml
