name: Ansible Windows Playbook Updated

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Configure SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Generate host file for dynamic inventory
        run: |
          cd /etc/ansible
          sudo chmod +x inventory.sh
          sudo sh inventory.sh
          #Check  inventory is generated  
          cat inventory.ini
 

      - name: Run Ansible playbook
        run: |
           ansible -i /etc/ansible/inventory.ini -m win_ping win
           ansible-playbook -i /etc/ansible/inventory.ini windowsplaybook.yaml
